services:
  - type: web
    name: grammar-corrector-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: chainlit run main.py --port 8000 --host 0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false
